BEGIN;

CREATE SCHEMA IF NOT EXISTS wialon;

CREATE TABLE IF NOT EXISTS wialon.ips_frames (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    remote_addr INET,
    imei VARCHAR(32),
    frame_type TEXT NOT NULL,
    frame TEXT NOT NULL,
    frame_hash CHAR(32) GENERATED ALWAYS AS (
        md5(
            coalesce(imei, '') || '|' ||
            coalesce(frame_type, '') || '|' ||
            coalesce(frame, '')
        )
    ) STORED,
    CONSTRAINT ips_frames_frame_type_not_empty CHECK (length(trim(frame_type)) > 0),
    CONSTRAINT ips_frames_frame_not_empty CHECK (length(frame) > 0)
);

CREATE INDEX IF NOT EXISTS idx_ips_frames_received_at
    ON wialon.ips_frames (received_at DESC);

CREATE INDEX IF NOT EXISTS idx_ips_frames_imei_received_at
    ON wialon.ips_frames (imei, received_at DESC)
    WHERE imei IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ips_frames_type_received_at
    ON wialon.ips_frames (frame_type, received_at DESC);

CREATE INDEX IF NOT EXISTS idx_ips_frames_hash
    ON wialon.ips_frames (frame_hash);

COMMIT;
