BEGIN;

CREATE TABLE IF NOT EXISTS wialon.sd_parsed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_frame_id BIGINT NOT NULL,
    imei VARCHAR(32) NOT NULL,
    frame_ts TIMESTAMPTZ NOT NULL,
    lat NUMERIC(9,6) NOT NULL,
    lon NUMERIC(9,6) NOT NULL,
    wifi_bssid MACADDR,
    wifi_rssi SMALLINT,
    wifi_chan SMALLINT,
    wifi_event TEXT,
    parsed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    dedup_key CHAR(32) GENERATED ALWAYS AS (
        md5(
            imei || '|' ||
            frame_ts::text || '|' ||
            lat::text || '|' ||
            lon::text || '|' ||
            coalesce(wifi_bssid::text, '') || '|' ||
            coalesce(wifi_rssi::text, '') || '|' ||
            coalesce(wifi_chan::text, '') || '|' ||
            coalesce(wifi_event, '')
        )
    ) STORED,
    CONSTRAINT sd_parsed_raw_fk
        FOREIGN KEY (raw_frame_id)
        REFERENCES wialon.ips_frames(id)
        ON DELETE CASCADE,
    CONSTRAINT sd_parsed_lat_range CHECK (lat BETWEEN -90 AND 90),
    CONSTRAINT sd_parsed_lon_range CHECK (lon BETWEEN -180 AND 180),
    CONSTRAINT sd_parsed_wifi_event_check CHECK (
        wifi_event IS NULL OR wifi_event IN ('appeared', 'disappeared', 'seen')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sd_parsed_raw_frame
    ON wialon.sd_parsed (raw_frame_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sd_parsed_dedup_key
    ON wialon.sd_parsed (dedup_key);

CREATE INDEX IF NOT EXISTS idx_sd_parsed_imei_frame_ts
    ON wialon.sd_parsed (imei, frame_ts DESC);

CREATE INDEX IF NOT EXISTS idx_sd_parsed_bssid_frame_ts
    ON wialon.sd_parsed (wifi_bssid, frame_ts DESC)
    WHERE wifi_bssid IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_sd_parsed_frame_ts
    ON wialon.sd_parsed (frame_ts DESC);

COMMIT;
