BEGIN;

CREATE TABLE IF NOT EXISTS wialon.wifi_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    event_ts TIMESTAMPTZ NOT NULL,
    imei VARCHAR(32) NOT NULL,
    bssid MACADDR NOT NULL,
    chan SMALLINT,
    rssi SMALLINT,
    source TEXT NOT NULL DEFAULT 'sd',
    raw_frame_id BIGINT,
    raw_received_at TIMESTAMPTZ,
    sd_parsed_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    dedup_key CHAR(32) GENERATED ALWAYS AS (
        md5(
            imei || '|' ||
            event_type || '|' ||
            event_ts::text || '|' ||
            bssid::text || '|' ||
            coalesce(chan::text, '') || '|' ||
            coalesce(rssi::text, '') || '|' ||
            coalesce(source, '')
        )
    ) STORED,
    CONSTRAINT wifi_events_event_type_check
        CHECK (event_type IN ('appeared', 'disappeared', 'seen')),
    CONSTRAINT wifi_events_source_not_empty
        CHECK (length(trim(source)) > 0),
    CONSTRAINT wifi_events_raw_fk
        FOREIGN KEY (raw_frame_id)
        REFERENCES wialon.ips_frames(id)
        ON DELETE SET NULL,
    CONSTRAINT wifi_events_sd_fk
        FOREIGN KEY (sd_parsed_id)
        REFERENCES wialon.sd_parsed(id)
        ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_wifi_events_sd_event
    ON wialon.wifi_events (sd_parsed_id, event_type, bssid)
    WHERE sd_parsed_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_wifi_events_raw_event
    ON wialon.wifi_events (raw_frame_id, event_type, bssid)
    WHERE raw_frame_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_wifi_events_dedup_key
    ON wialon.wifi_events (dedup_key);

CREATE INDEX IF NOT EXISTS idx_wifi_events_imei_event_ts
    ON wialon.wifi_events (imei, event_ts DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_wifi_events_bssid_event_ts
    ON wialon.wifi_events (bssid, event_ts DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_wifi_events_event_ts
    ON wialon.wifi_events (event_ts DESC);

COMMIT;
